---
version: '2'
services:
  editor:
    build:
      context: ../.
    image: kafka-avro-editor
    hostname: editor
    container_name: editor
    environment:
      - SCHEMA_REGISTRY_SERVER=http://localhost:8081
      #- SCHEMA_REGISTRY_USER=some_user
      #- SCHEMA_REGISTRY_PASSWORD=some_password
      - KAFKA_SERVER=localhost:9092
      #- KAFKA_SASL_MECHANISM=PLAIN
      #- KAFKA_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username\="some_user" password\="some_password"\;
      #- KAFKA_SECURITY_PROTOCOL=SASL_SSL
    network_mode: "host"
